# --- POSTGRESQL (Docker) ---
# Dev: senha fixa gestao123 (igual ao docker-compose). Para outro ambiente, defina POSTGRES_PASSWORD.

# AVISO: Mudei o localhost para o IP do servidor para não dar erro de conexão no Docker!
#spring.datasource.url=jdbc:postgresql://localhost:5434/gestao_mava
spring.datasource.url=jdbc:postgresql://192.168.0.7:5432/gestao_mava
#spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=gestao
spring.datasource.password=gestao123
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- CRITICO PARA O DATA.SQL FUNCIONAR ---
# 1. Mantem o esquema atualizado com as classes Java
spring.jpa.hibernate.ddl-auto=update

# 2. Espera o Hibernate criar as tabelas ANTES de rodar o script de dados
spring.jpa.defer-datasource-initialization=true 

# 3. Garante que acentos no script data.sql nao quebrem
spring.sql.init.encoding=UTF-8

# --- CONFIGURACAO DE VISUALIZACAO (THYMELEAF) ---
spring.thymeleaf.cache=false

# --- CONFIGURACAO DE UPLOAD DE ARQUIVOS ---
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CONFIG WHATSAPP
# Ajustado do localhost para o IP interno da máquina hospedeira
whatsapp.api.url=http://192.168.0.7:8081/api/sendText
whatsapp.instance=default
whatsapp.api.key=minhasenha123